// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: festival.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Client {
  public static partial class FestivalService
  {
    static readonly string __ServiceName = "festival.FestivalService";

    static readonly grpc::Marshaller<global::Client.LoginRequest> __Marshaller_festival_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.LoginReply> __Marshaller_festival_LoginReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.LoginReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.SaveBiletRequest> __Marshaller_festival_SaveBiletRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.SaveBiletRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.SaveBiletReply> __Marshaller_festival_SaveBiletReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.SaveBiletReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.FindSpectacolRequest> __Marshaller_festival_FindSpectacolRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.FindSpectacolRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.FindSpectacolReply> __Marshaller_festival_FindSpectacolReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.FindSpectacolReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.GetAllRequest> __Marshaller_festival_GetAllRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.GetAllRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.GetAllReply> __Marshaller_festival_GetAllReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.GetAllReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.GetAllByDateRequest> __Marshaller_festival_GetAllByDateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.GetAllByDateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Client.GetAllByDateReply> __Marshaller_festival_GetAllByDateReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Client.GetAllByDateReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Client.LoginRequest, global::Client.LoginReply> __Method_login = new grpc::Method<global::Client.LoginRequest, global::Client.LoginReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "login",
        __Marshaller_festival_LoginRequest,
        __Marshaller_festival_LoginReply);

    static readonly grpc::Method<global::Client.SaveBiletRequest, global::Client.SaveBiletReply> __Method_saveBilet = new grpc::Method<global::Client.SaveBiletRequest, global::Client.SaveBiletReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "saveBilet",
        __Marshaller_festival_SaveBiletRequest,
        __Marshaller_festival_SaveBiletReply);

    static readonly grpc::Method<global::Client.FindSpectacolRequest, global::Client.FindSpectacolReply> __Method_findSpectacol = new grpc::Method<global::Client.FindSpectacolRequest, global::Client.FindSpectacolReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "findSpectacol",
        __Marshaller_festival_FindSpectacolRequest,
        __Marshaller_festival_FindSpectacolReply);

    static readonly grpc::Method<global::Client.GetAllRequest, global::Client.GetAllReply> __Method_getAllSpectacol = new grpc::Method<global::Client.GetAllRequest, global::Client.GetAllReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getAllSpectacol",
        __Marshaller_festival_GetAllRequest,
        __Marshaller_festival_GetAllReply);

    static readonly grpc::Method<global::Client.GetAllByDateRequest, global::Client.GetAllByDateReply> __Method_getSpectacolByDate = new grpc::Method<global::Client.GetAllByDateRequest, global::Client.GetAllByDateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getSpectacolByDate",
        __Marshaller_festival_GetAllByDateRequest,
        __Marshaller_festival_GetAllByDateReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Client.FestivalReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FestivalService</summary>
    [grpc::BindServiceMethod(typeof(FestivalService), "BindService")]
    public abstract partial class FestivalServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Client.LoginReply> login(global::Client.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task saveBilet(grpc::IAsyncStreamReader<global::Client.SaveBiletRequest> requestStream, grpc::IServerStreamWriter<global::Client.SaveBiletReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Client.FindSpectacolReply> findSpectacol(global::Client.FindSpectacolRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Client.GetAllReply> getAllSpectacol(global::Client.GetAllRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Client.GetAllByDateReply> getSpectacolByDate(global::Client.GetAllByDateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FestivalService</summary>
    public partial class FestivalServiceClient : grpc::ClientBase<FestivalServiceClient>
    {
      /// <summary>Creates a new client for FestivalService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FestivalServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FestivalService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FestivalServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FestivalServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FestivalServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Client.LoginReply login(global::Client.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Client.LoginReply login(global::Client.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Client.LoginReply> loginAsync(global::Client.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return loginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Client.LoginReply> loginAsync(global::Client.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_login, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Client.SaveBiletRequest, global::Client.SaveBiletReply> saveBilet(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return saveBilet(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Client.SaveBiletRequest, global::Client.SaveBiletReply> saveBilet(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_saveBilet, null, options);
      }
      public virtual global::Client.FindSpectacolReply findSpectacol(global::Client.FindSpectacolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return findSpectacol(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Client.FindSpectacolReply findSpectacol(global::Client.FindSpectacolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_findSpectacol, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Client.FindSpectacolReply> findSpectacolAsync(global::Client.FindSpectacolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return findSpectacolAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Client.FindSpectacolReply> findSpectacolAsync(global::Client.FindSpectacolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_findSpectacol, null, options, request);
      }
      public virtual global::Client.GetAllReply getAllSpectacol(global::Client.GetAllRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllSpectacol(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Client.GetAllReply getAllSpectacol(global::Client.GetAllRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getAllSpectacol, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Client.GetAllReply> getAllSpectacolAsync(global::Client.GetAllRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getAllSpectacolAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Client.GetAllReply> getAllSpectacolAsync(global::Client.GetAllRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getAllSpectacol, null, options, request);
      }
      public virtual global::Client.GetAllByDateReply getSpectacolByDate(global::Client.GetAllByDateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getSpectacolByDate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Client.GetAllByDateReply getSpectacolByDate(global::Client.GetAllByDateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getSpectacolByDate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Client.GetAllByDateReply> getSpectacolByDateAsync(global::Client.GetAllByDateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getSpectacolByDateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Client.GetAllByDateReply> getSpectacolByDateAsync(global::Client.GetAllByDateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getSpectacolByDate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FestivalServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FestivalServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FestivalServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_login, serviceImpl.login)
          .AddMethod(__Method_saveBilet, serviceImpl.saveBilet)
          .AddMethod(__Method_findSpectacol, serviceImpl.findSpectacol)
          .AddMethod(__Method_getAllSpectacol, serviceImpl.getAllSpectacol)
          .AddMethod(__Method_getSpectacolByDate, serviceImpl.getSpectacolByDate).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FestivalServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Client.LoginRequest, global::Client.LoginReply>(serviceImpl.login));
      serviceBinder.AddMethod(__Method_saveBilet, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Client.SaveBiletRequest, global::Client.SaveBiletReply>(serviceImpl.saveBilet));
      serviceBinder.AddMethod(__Method_findSpectacol, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Client.FindSpectacolRequest, global::Client.FindSpectacolReply>(serviceImpl.findSpectacol));
      serviceBinder.AddMethod(__Method_getAllSpectacol, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Client.GetAllRequest, global::Client.GetAllReply>(serviceImpl.getAllSpectacol));
      serviceBinder.AddMethod(__Method_getSpectacolByDate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Client.GetAllByDateRequest, global::Client.GetAllByDateReply>(serviceImpl.getSpectacolByDate));
    }

  }
}
#endregion
